
import { Subject, Chapter, PastPaper, Note, MockTest, Question } from '@/types';

export const subjects: Subject[] = [
  {
    id: 'phy',
    name: 'Physics',
    slug: 'physics',
    icon: 'atom',
    description: 'Mechanics, Thermodynamics, Electricity & Magnetism, and Modern Physics.',
    totalChapters: 24,
  },
  {
    id: 'chem',
    name: 'Chemistry',
    slug: 'chemistry',
    icon: 'flask',
    description: 'Physical, Organic, and Inorganic Chemistry concepts and reactions.',
    totalChapters: 20,
  },
  {
    id: 'bio',
    name: 'Biology',
    slug: 'biology',
    icon: 'microscope',
    description: 'Botany and Zoology: Cell biology, Genetics, Ecology, and Human Physiology.',
    totalChapters: 18,
  },
  {
    id: 'math',
    name: 'Mathematics',
    slug: 'mathematics',
    icon: 'calculator',
    description: 'Calculus, Algebra, Coordinate Geometry, and Vectors.',
    totalChapters: 15,
  },
  {
    id: 'cs',
    name: 'Computer Science',
    slug: 'computer-science',
    icon: 'monitor',
    description: 'C Programming, Web Technology (HTML/CSS), Database (SQL), and Python.',
    totalChapters: 12,
  },
  {
    id: 'eng',
    name: 'English',
    slug: 'english',
    icon: 'book',
    description: 'Language Development and Literature (Grade 11 & 12).',
    totalChapters: 24,
  },
  {
    id: 'nep',
    name: 'Nepali',
    slug: 'nepali',
    icon: 'book',
    description: 'Compulsory Nepali chapters and exercises (Grade 11 & 12).',
    totalChapters: 24,
  },
];

export const chapters: Chapter[] = [
  // Physics - Grade 11
  { id: 'phy-11-1', subjectId: 'phy', number: 1, title: 'Units and Measurement', description: 'Fundamental and derived units, dimensions, and error analysis.', estimatedHours: 4, grade: 11 },
  { id: 'phy-11-2', subjectId: 'phy', number: 2, title: 'Vectors and Scalars', description: 'Vector addition, subtraction, dot and cross products.', estimatedHours: 6, grade: 11 },
  { id: 'phy-11-3', subjectId: 'phy', number: 3, title: 'Kinematics', description: 'Motion in one and two dimensions, projectile motion.', estimatedHours: 8, grade: 11 },
  { id: 'phy-11-4', subjectId: 'phy', number: 4, title: 'Laws of Motion', description: 'Newtons laws, friction, and circular motion.', estimatedHours: 8, grade: 11 },
  { id: 'phy-11-5', subjectId: 'phy', number: 5, title: 'Work, Energy and Power', description: 'Work done by constant and variable forces, kinetic and potential energy.', estimatedHours: 7, grade: 11 },
  
  // Physics - Grade 12
  { id: 'phy-12-1', subjectId: 'phy', number: 6, title: 'Wave Optics', description: 'Interference, Diffraction, Polarization of light.', estimatedHours: 10, grade: 12 },
  { id: 'phy-12-2', subjectId: 'phy', number: 7, title: 'Current Electricity', description: 'Ohm’s law, Kirchhoff’s laws, Potentiometer.', estimatedHours: 12, grade: 12 },
  { id: 'phy-12-3', subjectId: 'phy', number: 8, title: 'Modern Physics', description: 'Photoelectric effect, Bohr’s model, X-rays.', estimatedHours: 10, grade: 12 },

  // Chemistry - Grade 11
  { id: 'chem-11-1', subjectId: 'chem', number: 1, title: 'Stoichiometry', description: 'Mole concept, chemical equations, and calculations.', estimatedHours: 6, grade: 11 },
  { id: 'chem-11-2', subjectId: 'chem', number: 2, title: 'Atomic Structure', description: 'Bohr model, quantum numbers, and electronic configuration.', estimatedHours: 8, grade: 11 },
  { id: 'chem-11-3', subjectId: 'chem', number: 3, title: 'Chemical Bonding', description: 'Ionic, covalent, and coordinate bonds, VSEPR theory.', estimatedHours: 10, grade: 11 },
  { id: 'chem-11-4', subjectId: 'chem', number: 4, title: 'States of Matter', description: 'Gaseous state, liquid state, and solid state properties.', estimatedHours: 8, grade: 11 },

  // Chemistry - Grade 12
  { id: 'chem-12-1', subjectId: 'chem', number: 5, title: 'Volumetric Analysis', description: 'Titration, acid-base reactions, redox titration.', estimatedHours: 8, grade: 12 },
  { id: 'chem-12-2', subjectId: 'chem', number: 6, title: 'Organic Chemistry II', description: 'Haloalkanes, Alcohols, Phenols, Ethers.', estimatedHours: 15, grade: 12 },

  // Biology - Grade 11
  { id: 'bio-11-1', subjectId: 'bio', number: 1, title: 'Cell Biology', description: 'Structure and function of cell organelles, cell division.', estimatedHours: 8, grade: 11 },
  { id: 'bio-11-2', subjectId: 'bio', number: 2, title: 'Genetics', description: 'Mendelian genetics, DNA structure, and replication.', estimatedHours: 10, grade: 11 },
  
  // Biology - Grade 12
  { id: 'bio-12-1', subjectId: 'bio', number: 3, title: 'Human Physiology', description: 'Digestion, respiration, circulation, and excretion systems.', estimatedHours: 15, grade: 12 },
  { id: 'bio-12-2', subjectId: 'bio', number: 4, title: 'Genetics and Evolution', description: 'Molecular basis of inheritance, Evolution theories.', estimatedHours: 12, grade: 12 },

  // Math - Grade 11
  { id: 'math-11-1', subjectId: 'math', number: 1, title: 'Sequence and Series', description: 'AP, GP, HP, and special series.', estimatedHours: 6, grade: 11 },
  { id: 'math-11-2', subjectId: 'math', number: 2, title: 'Matrices and Determinants', description: 'Properties, inverse, and system of linear equations.', estimatedHours: 8, grade: 11 },
  { id: 'math-11-3', subjectId: 'math', number: 3, title: 'Calculus: Limits and Continuity', description: 'Concept of limits, continuity, and derivatives.', estimatedHours: 12, grade: 11 },

  // Math - Grade 12
  { id: 'math-12-1', subjectId: 'math', number: 4, title: 'Permutation and Combination', description: 'Counting principles, binomial theorem.', estimatedHours: 8, grade: 12 },
  { id: 'math-12-2', subjectId: 'math', number: 5, title: 'Integrals', description: 'Definite and indefinite integrals, applications.', estimatedHours: 15, grade: 12 },

  // CS - Grade 11
  { id: 'cs-11-1', subjectId: 'cs', number: 1, title: 'Computer System Architecture', description: 'Logic gates, boolean algebra, and CPU architecture.', estimatedHours: 6, grade: 11 },
  { id: 'cs-11-2', subjectId: 'cs', number: 2, title: 'Web Technology I', description: 'Introduction to HTML, CSS basics.', estimatedHours: 8, grade: 11 },
  { id: 'cs-11-3', subjectId: 'cs', number: 3, title: 'Programming in C', description: 'Flowcharts, Algorithms, C syntax, Control structures.', estimatedHours: 12, grade: 11 },

  // CS - Grade 12
  { id: 'cs-12-1', subjectId: 'cs', number: 4, title: 'Database Management System (SQL)', description: 'DBMS concepts, normalization, and SQL queries.', estimatedHours: 10, grade: 12 },
  { id: 'cs-12-2', subjectId: 'cs', number: 5, title: 'Web Technology II', description: 'PHP, JavaScript basics.', estimatedHours: 10, grade: 12 },
  { id: 'cs-12-3', subjectId: 'cs', number: 6, title: 'Programming in C (Advanced)', description: 'Pointers, Structures, File Handling.', estimatedHours: 12, grade: 12 },
  
  // English - Grade 11 (Language Development Units 1–20)
  { id: 'eng-11-1', subjectId: 'eng', number: 1, title: 'Education and Humanity', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-2', subjectId: 'eng', number: 2, title: 'Communication', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-3', subjectId: 'eng', number: 3, title: 'Media and Society', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-4', subjectId: 'eng', number: 4, title: 'History and Culture', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-5', subjectId: 'eng', number: 5, title: 'Life and Love', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-6', subjectId: 'eng', number: 6, title: 'Health and Exercise', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-7', subjectId: 'eng', number: 7, title: 'Ecology and Development', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-8', subjectId: 'eng', number: 8, title: 'Humour and Satire', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-9', subjectId: 'eng', number: 9, title: 'Democracy and Human Rights', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-10', subjectId: 'eng', number: 10, title: 'Home Life and Family Relationship', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-11', subjectId: 'eng', number: 11, title: 'Arts and Creations', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-12', subjectId: 'eng', number: 12, title: 'Fantasy', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-13', subjectId: 'eng', number: 13, title: 'Career and Entrepreneurship', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-14', subjectId: 'eng', number: 14, title: 'Power and Politics', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-15', subjectId: 'eng', number: 15, title: 'War and Peace', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-16', subjectId: 'eng', number: 16, title: 'Critical Thinking', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-17', subjectId: 'eng', number: 17, title: 'Globalisation and Diaspora', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-18', subjectId: 'eng', number: 18, title: 'Immigration and Identity', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-19', subjectId: 'eng', number: 19, title: 'Travel and Tourism', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  { id: 'eng-11-20', subjectId: 'eng', number: 20, title: 'Science and Technology', description: 'Language Development unit exercises and summary.', estimatedHours: 4, grade: 11 },
  // English - Grade 11 Literature (category chapters)
  { id: 'eng-11-lit-ss', subjectId: 'eng', number: 21, title: 'Short Stories (Overview)', description: '7 stories: The Selfish Giant, The Oval Portrait, etc.', estimatedHours: 6, grade: 11 },
  { id: 'eng-11-lit-poems', subjectId: 'eng', number: 22, title: 'Poems (Overview)', description: '5 poems: Corona Says, A Red, Red Rose, etc.', estimatedHours: 5, grade: 11 },
  { id: 'eng-11-lit-essays', subjectId: 'eng', number: 23, title: 'Essays (Overview)', description: '5 essays: Sharing Tradition, How to Live Before You Die, etc.', estimatedHours: 6, grade: 11 },
  { id: 'eng-11-lit-plays', subjectId: 'eng', number: 24, title: 'One Act Plays (Overview)', description: '3 plays: Trifles, A Sunny Morning, Refund.', estimatedHours: 5, grade: 11 },
  // Nepali - Grade 11 (12 chapters)
  { id: 'nep-11-1', subjectId: 'nep', number: 1, title: 'वीर पुर्खा (कविता)', description: 'कविता — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-2', subjectId: 'nep', number: 2, title: 'गाउँको माया (सामाजिक कथा)', description: 'कथा — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-3', subjectId: 'nep', number: 3, title: 'संस्कृतिको नयाँ यात्रा (आत्मपरक निबन्ध)', description: 'निबन्ध — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-4', subjectId: 'nep', number: 4, title: 'योगमाया (राष्ट्रिय जीवनी)', description: 'जीवनी — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-5', subjectId: 'nep', number: 5, title: 'साथीलाई चिठी (चिठी)', description: 'चिठी — अभ्यास र सार', estimatedHours: 3, grade: 11 },
  { id: 'nep-11-6', subjectId: 'nep', number: 6, title: 'त्यो फेरि फर्कला ? (मनोवैज्ञानिक कथा)', description: 'कथा — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-7', subjectId: 'nep', number: 7, title: 'पर्यापर्यटनका सम्भावना र आयाम (वस्तुपरक निबन्ध)', description: 'निबन्ध — अभ्यास र सार', estimatedHours: 6, grade: 11 },
  { id: 'nep-11-8', subjectId: 'nep', number: 8, title: 'लौ आयो ताजा खबर (लघु नाटक)', description: 'नाटक — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-9', subjectId: 'nep', number: 9, title: 'सफलताको कथा (रिपोर्ताजमूलक रचना)', description: 'रिपोर्टाज — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-10', subjectId: 'nep', number: 10, title: 'कृषिशालामा एक दिन (संवाद)', description: 'संवाद — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-11', subjectId: 'nep', number: 11, title: 'रारा भ्रमण (दैनिकी)', description: 'दैनिकी — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  { id: 'nep-11-12', subjectId: 'nep', number: 12, title: 'जलस्रोत र ऊर्जा (वक्तृता)', description: 'वक्तृता — अभ्यास र सार', estimatedHours: 4, grade: 11 },
  // Nepali - Grade 12 (12 chapters)
  { id: 'nep-12-1', subjectId: 'nep', number: 13, title: 'आमाको सपना', description: 'कविता/रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-2', subjectId: 'nep', number: 14, title: 'विरहिणी दमयन्ती', description: 'महाभारत पात्र — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-3', subjectId: 'nep', number: 15, title: 'घनघस्याको उकालो काट्ता', description: 'कथा/रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-4', subjectId: 'nep', number: 16, title: 'व्यावसायिक पत्र', description: 'पत्र — अभ्यास र सार', estimatedHours: 3, grade: 12 },
  { id: 'nep-12-5', subjectId: 'nep', number: 17, title: 'एक चिहान', description: 'कथा — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-6', subjectId: 'nep', number: 18, title: 'स्टिफन विलियम हकिङ', description: 'व्यक्तित्व — अभ्यास र सार', estimatedHours: 3, grade: 12 },
  { id: 'nep-12-7', subjectId: 'nep', number: 19, title: 'हामीलाई बोलाउँछन् हिमचुली', description: 'रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-8', subjectId: 'nep', number: 20, title: 'मातृत्व', description: 'रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-9', subjectId: 'nep', number: 21, title: 'गोर्खे', description: 'रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-10', subjectId: 'nep', number: 22, title: 'नेपाली पहिचान', description: 'रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
  { id: 'nep-12-11', subjectId: 'nep', number: 23, title: 'सहकारी', description: 'रचना — अभ्यास र सार', estimatedHours: 3, grade: 12 },
  { id: 'nep-12-12', subjectId: 'nep', number: 24, title: 'जीवन मार्ग', description: 'रचना — अभ्यास र सार', estimatedHours: 4, grade: 12 },
];

export const notes: Note[] = [
  {
    id: 'note-phy-11-1',
    chapterId: 'phy-11-1',
    type: 'theory',
    title: 'Introduction to Units',
    content: 'Physical quantities are classified into fundamental and derived quantities. The SI system is the standard used globally. Fundamental units include Meter (m), Kilogram (kg), Second (s), Ampere (A), Kelvin (K), Mole (mol), and Candela (cd).',
  },
  {
    id: 'note-phy-11-2',
    chapterId: 'phy-11-1',
    type: 'formula',
    title: 'Dimensional Analysis Formulas',
    content: '<ul><li>Dimension of Force = [MLT^-2]</li><li>Dimension of Energy = [ML^2T^-2]</li><li>Dimension of Power = [ML^2T^-3]</li><li>Dimension of Pressure = [ML^-1T^-2]</li></ul>',
  },
  {
    id: 'note-chem-11-1',
    chapterId: 'chem-11-1',
    type: 'theory',
    title: 'The Mole Concept',
    content: 'One mole contains 6.022 x 10^23 particles. This number is known as Avogadros constant. Molar mass is the mass of one mole of a substance in grams.',
  },
  {
    id: 'note-cs-11-3-1',
    chapterId: 'cs-11-3',
    type: 'theory',
    title: 'Introduction to C',
    content: 'C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system. It was developed by Dennis Ritchie at Bell Labs.',
  },
  {
    id: 'note-cs-11-3-2',
    chapterId: 'cs-11-3',
    type: 'theory',
    title: 'Control Structures',
    content: 'Control structures in C include: <ul><li><strong>if-else</strong>: Conditional execution</li><li><strong>switch</strong>: Multi-way branching</li><li><strong>loops</strong>: for, while, do-while</li></ul>',
  },
  {
    id: 'note-cs-11-2-1',
    chapterId: 'cs-11-2',
    type: 'theory',
    title: 'HTML Structure',
    content: 'HTML (HyperText Markup Language) is the standard markup language for documents designed to be displayed in a web browser. Key tags include &lt;html&gt;, &lt;head&gt;, &lt;body&gt;, &lt;div&gt;, &lt;span&gt;.',
  },
  {
    id: 'note-cs-12-1-1',
    chapterId: 'cs-12-1',
    type: 'theory',
    title: 'SQL Commands',
    content: 'SQL commands are grouped into: <ul><li><strong>DDL</strong>: CREATE, ALTER, DROP</li><li><strong>DML</strong>: SELECT, INSERT, UPDATE, DELETE</li><li><strong>DCL</strong>: GRANT, REVOKE</li></ul>',
  },
  {
    id: 'note-phy-11-2-1',
    chapterId: 'phy-11-2',
    type: 'theory',
    title: 'Scalars and Vectors',
    content: '<p>Scalars have magnitude only (e.g., mass, temperature). Vectors have magnitude and direction (e.g., displacement, velocity, force). A vector is represented graphically by an arrow; its length denotes magnitude and its orientation denotes direction.</p><p>Vector addition follows the parallelogram or triangle law. Resultant R of A and B: <em>R = A + B</em>. Subtraction uses <em>A − B = A + (−B)</em>.</p><p>Dot product: <em>A · B = |A||B|cosθ</em>. Cross product: <em>A × B = |A||B|sinθ n̂</em>.</p>',
  },
  {
    id: 'note-phy-11-2-2',
    chapterId: 'phy-11-2',
    type: 'formula',
    title: 'Vector Identities',
    content: '<ul><li>Unit vector: <em>â = A/|A|</em></li><li>Magnitude of cross product: <em>|A × B| = |A||B|sinθ</em></li><li>Scalar projection: <em>comp<sub>B</sub>(A) = (A · B)/|B|</em></li><li>Vector projection: <em>proj<sub>B</sub>(A) = ((A · B)/|B|^2) B</em></li></ul>',
  },
  {
    id: 'note-phy-11-3-1',
    chapterId: 'phy-11-3',
    type: 'theory',
    title: 'Kinematics Basics',
    content: '<p>Kinematics describes motion without considering causes. Key quantities: displacement, velocity, and acceleration.</p><p>For uniform acceleration in one dimension, motion is described by the equations of motion. Projectile motion decomposes into independent horizontal and vertical components.</p>',
  },
  {
    id: 'note-phy-11-3-2',
    chapterId: 'phy-11-3',
    type: 'formula',
    title: 'Equations of Motion',
    content: '<ul><li><em>v = u + at</em></li><li><em>s = ut + ½at^2</em></li><li><em>v^2 = u^2 + 2as</em></li><li>Projectile time of flight: <em>T = (2u sinθ)/g</em></li><li>Range: <em>R = (u^2 sin2θ)/g</em></li></ul>',
  },
  {
    id: 'note-chem-11-2-1',
    chapterId: 'chem-11-2',
    type: 'theory',
    title: 'Quantum Numbers',
    content: '<p>Each electron in an atom is described by four quantum numbers: n (principal), l (azimuthal), m<sub>l</sub> (magnetic), and m<sub>s</sub> (spin). They define energy level, subshell shape, orientation, and spin.</p><p>Pauli exclusion states no two electrons can have the same set of four quantum numbers. Hund’s rule favors maximum multiplicity in degenerate orbitals.</p>',
  },
  {
    id: 'note-math-11-1-1',
    chapterId: 'math-11-1',
    type: 'theory',
    title: 'Arithmetic Progression',
    content: '<p>An AP has a constant difference d between consecutive terms. If a is the first term, the n-th term is <em>T<sub>n</sub> = a + (n−1)d</em>.</p><p>Sum of first n terms: <em>S<sub>n</sub> = n/2[2a + (n−1)d]</em>.</p>',
  },
  {
    id: 'note-cs-11-1-1',
    chapterId: 'cs-11-1',
    type: 'theory',
    title: 'Logic Gates Overview',
    content: '<p>Basic gates: AND, OR, NOT; derived gates: NAND, NOR, XOR, XNOR. Truth tables define gate behavior. Boolean algebra simplifies logical expressions for digital circuit design.</p>',
  },
  {
    id: 'note-bio-11-1-1',
    chapterId: 'bio-11-1',
    type: 'theory',
    title: 'Cell Organelles',
    content: '<p>Key organelles: nucleus (genetic control), mitochondria (ATP production), ribosomes (protein synthesis), ER and Golgi (processing and transport), lysosomes (digestion), chloroplasts in plants (photosynthesis).</p>',
  },
  {
    id: 'note-phy-11-1-wiki-1',
    chapterId: 'phy-11-1',
    type: 'theory',
    title: 'SI Base Units Overview',
    content: '<p>The International System of Units (SI) defines seven base units: second (time), metre (length), kilogram (mass), ampere (electric current), kelvin (thermodynamic temperature), mole (amount of substance), and candela (luminous intensity). All other units are derived from these.</p><p>Source: <a href="https://en.wikipedia.org/wiki/SI_base_unit" target="_blank" rel="noopener noreferrer">Wikipedia — SI base unit</a></p>',
  },
  {
    id: 'note-chem-11-1-wiki-1',
    chapterId: 'chem-11-1',
    type: 'theory',
    title: 'Stoichiometry Basics',
    content: '<p>Stoichiometry studies quantitative relationships between reactants and products using balanced chemical equations and the conservation of mass. It relates moles, molar ratios, and masses to predict product amounts and required reactant quantities.</p><p>Source: <a href="https://en.wikipedia.org/wiki/Stoichiometry" target="_blank" rel="noopener noreferrer">Wikipedia — Stoichiometry</a></p>',
  },
  { id: 'note-eng-11-1', chapterId: 'eng-11-1', type: 'theory', title: 'Education and Humanity — Overview', content: '<p>Unit summary and exercises with vocabulary, grammar, and comprehension.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/education-and-humanity/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-2', chapterId: 'eng-11-2', type: 'theory', title: 'Communication — Overview', content: '<p>Unit summary and practice tasks focused on communication skills.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/communication/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-3', chapterId: 'eng-11-3', type: 'theory', title: 'Media and Society — Overview', content: '<p>Unit summary: media influence, society, and critical reading.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/media-and-society/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-4', chapterId: 'eng-11-4', type: 'theory', title: 'History and Culture — Overview', content: '<p>Unit summary with thematic text and comprehension exercises.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/history-and-culture/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-5', chapterId: 'eng-11-5', type: 'theory', title: 'Life and Love — Overview', content: '<p>Unit summary: vocabulary and comprehension about life and love.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/life-and-love/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-6', chapterId: 'eng-11-6', type: 'theory', title: 'Health and Exercise — Overview', content: '<p>Unit summary: health, wellness, and grammar exercises.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/health-and-exercise/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-7', chapterId: 'eng-11-7', type: 'theory', title: 'Ecology and Development — Overview', content: '<p>Unit summary: ecology topics with reading and writing practice.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/ecology-and-development/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-8', chapterId: 'eng-11-8', type: 'theory', title: 'Humour and Satire — Overview', content: '<p>Unit summary with exercises on humour and satire.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/humour-and-satire/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-9', chapterId: 'eng-11-9', type: 'theory', title: 'Democracy and Human Rights — Overview', content: '<p>Unit summary: rights, democracy, and critical thinking tasks.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/democracy-and-human-rights/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-10', chapterId: 'eng-11-10', type: 'theory', title: 'Home Life and Family Relationship — Overview', content: '<p>Unit summary with exercises about family life and relationships.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/home-life-and-family-relationship/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-11', chapterId: 'eng-11-11', type: 'theory', title: 'Arts and Creations — Overview', content: '<p>Unit summary on arts and creative expression.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/arts-and-creations/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-12', chapterId: 'eng-11-12', type: 'theory', title: 'Fantasy — Overview', content: '<p>Unit summary with reading comprehension and vocabulary.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/fantasy/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-13', chapterId: 'eng-11-13', type: 'theory', title: 'Career and Entrepreneurship — Overview', content: '<p>Unit summary on careers and entrepreneurship; practice tasks.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/career-and-entrepreneurship/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-14', chapterId: 'eng-11-14', type: 'theory', title: 'Power and Politics — Overview', content: '<p>Unit summary with exercises on power and politics.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/power-and-politics/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-15', chapterId: 'eng-11-15', type: 'theory', title: 'War and Peace — Overview', content: '<p>Unit summary; reading and writing practice.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/war-and-peace/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-16', chapterId: 'eng-11-16', type: 'theory', title: 'Critical Thinking — Overview', content: '<p>Unit summary developing critical reasoning skills.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/critical-thinking/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-17', chapterId: 'eng-11-17', type: 'theory', title: 'Globalisation and Diaspora — Overview', content: '<p>Unit summary: globalization, diaspora; vocabulary tasks.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/globalisation-and-diaspora/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-18', chapterId: 'eng-11-18', type: 'theory', title: 'Immigration and Identity — Overview', content: '<p>Unit summary; identity themes with exercises.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/immigration-and-identity/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-19', chapterId: 'eng-11-19', type: 'theory', title: 'Travel and Tourism — Overview', content: '<p>Unit summary; reading comprehension on travel/tourism.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/travel-and-tourism/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-20', chapterId: 'eng-11-20', type: 'theory', title: 'Science and Technology — Overview', content: '<p>Unit summary; key vocabulary and comprehension pointers.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/science-and-technology/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-eng-11-lit-ss', chapterId: 'eng-11-lit-ss', type: 'theory', title: 'Short Stories — Overview', content: '<p>7 stories with complete exercise solutions (e.g., The Selfish Giant, The Oval Portrait).</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — English</a></p>' },
  { id: 'note-eng-11-lit-poems', chapterId: 'eng-11-lit-poems', type: 'theory', title: 'Poems — Overview', content: '<p>5 poems with summary and exercises (e.g., Corona Says, A Red, Red Rose).</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — English</a></p>' },
  { id: 'note-eng-11-lit-essays', chapterId: 'eng-11-lit-essays', type: 'theory', title: 'Essays — Overview', content: '<p>5 essays with complete exercises (e.g., Sharing Tradition, How to Live Before You Die).</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — English</a></p>' },
  { id: 'note-eng-11-lit-plays', chapterId: 'eng-11-lit-plays', type: 'theory', title: 'One Act Plays — Overview', content: '<p>3 plays: Trifles, A Sunny Morning, Refund — exercise solutions available.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — English</a></p>' },
  {
    id: 'note-eng-11-20-1',
    chapterId: 'eng-11-20',
    type: 'theory',
    title: 'Science and Technology — Key Vocabulary',
    content: '<p>Freshman: first-year student; Naive: lacking experience; Dorm: student residence; Suitemate: someone sharing suite facilities; Incalculable: cannot be measured; Brag: boast; Disposal: throwing away.</p><p>Exercises and comprehension adapted from NEB Plus 2 Notes.</p><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/science-and-technology/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Science and Technology</a></p>',
  },
  {
    id: 'note-eng-11-20-2',
    chapterId: 'eng-11-20',
    type: 'theory',
    title: 'Science and Technology — Comprehension Summary',
    content: '<p>The piece contrasts a parent\'s college experience with modern tech-driven student life, noting increased connectivity but fragmented real-world interactions.</p><ul><li>Tools: mobile apps, social media, YouTube</li><li>Impacts: reliance on shortcuts, reduced exploration</li></ul><p>Source: <a href="https://nebplus2notes.com/class-11/english/ld/science-and-technology/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>',
  },
  {
    id: 'note-nep-11-7-1',
    chapterId: 'nep-11-7',
    type: 'theory',
    title: 'पर्यापर्यटन — शब्दभण्डार',
    content: '<p>विहङ्गम दृष्टि: चराले जस्तै माथिबाट हेर्ने दृष्टि; तृणहारी: घाँसपात खाने; पर्यापर्यटन: विविधताका कारण हुने पर्यटन; जलक्रीडा: पानीमा खेलिने खेलहरू; पर्यावरणमैत्री: वातावरण सुहाउँदो।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/paryatan-samvawana-ra-aayam/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — पर्यापर्यटनका सम्भावना र आयाम</a></p>',
  },
  {
    id: 'note-nep-11-7-2',
    chapterId: 'nep-11-7',
    type: 'theory',
    title: 'पर्यापर्यटन — बोध/अभिव्यक्ति सार',
    content: '<p>पाठ दस अनुच्छेदमा संरचित छ। पर्यापर्यटनले स्थानीय विविधता, पर्यावरणमैत्री गतिविधि, जलक्रीडा, र पहाडी/तराई क्षेत्रका विशेषताको उपयोग गर्छ।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/paryatan-samvawana-ra-aayam/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>',
  },
  { id: 'note-nep-11-1', chapterId: 'nep-11-1', type: 'theory', title: 'वीर पुर्खा — सार', content: '<p>कविता अध्यायको सार तथा अभ्यास द्रुत पुनरावर्तनका लागि।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-2', chapterId: 'nep-11-2', type: 'theory', title: 'गाउँको माया — सार', content: '<p>कथाको सार र मुख्य शब्दावली अभ्यासहरूको झलक।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-3', chapterId: 'nep-11-3', type: 'theory', title: 'संस्कृतिको नयाँ यात्रा — सार', content: '<p>आत्मपरक निबन्धको सार र अभ्यास बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/sanskriti-ko-naya-yatra/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-11-4', chapterId: 'nep-11-4', type: 'theory', title: 'योगमाया — सार', content: '<p>राष्ट्रिय जीवनी अध्यायको सार र शब्दभण्डार।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-5', chapterId: 'nep-11-5', type: 'theory', title: 'साथीलाई चिठी — सार', content: '<p>चिठी अध्यायको मुख्य बुँदाहरू र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-6', chapterId: 'nep-11-6', type: 'theory', title: 'त्यो फेरि फर्कला ? — सार', content: '<p>मनोवैज्ञानिक कथाको सार र अभ्यास दृष्टान्त।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-8', chapterId: 'nep-11-8', type: 'theory', title: 'लौ आयो ताजा खबर — सार', content: '<p>लघु नाटकको सार र अभ्यास बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-9', chapterId: 'nep-11-9', type: 'theory', title: 'सफलताको कथा — सार', content: '<p>रिपोर्ताजमूलक रचनाको सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-11-10', chapterId: 'nep-11-10', type: 'theory', title: 'कृषिशालामा एक दिन — सार', content: '<p>संवाद अध्यायको सार र महत्वपूर्ण शब्दभण्डार।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/krishisala-ma-yek-din/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-11-11', chapterId: 'nep-11-11', type: 'theory', title: 'रारा भ्रमण — सार', content: '<p>दैनिकी अध्यायको सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/rara-vramad/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-11-12', chapterId: 'nep-11-12', type: 'theory', title: 'जलस्रोत र ऊर्जा — सार', content: '<p>वक्तृता अध्यायको सार र अभ्यास बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-11/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-1', chapterId: 'nep-12-1', type: 'theory', title: 'आमाको सपना — सार', content: '<p>अध्याय सार र अभ्यास झलक।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/aama-ko-sapana/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-12-2', chapterId: 'nep-12-2', type: 'theory', title: 'विरहिणी दमयन्ती — सार', content: '<p>अध्याय सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/birhidi-damyenti/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-12-3', chapterId: 'nep-12-3', type: 'theory', title: 'घनघस्याको उकालो काट्ता — सार', content: '<p>अध्याय सार र शब्दभण्डार।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-4', chapterId: 'nep-12-4', type: 'theory', title: 'व्यावसायिक पत्र — सार', content: '<p>अध्याय सार र अभ्यास बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-5', chapterId: 'nep-12-5', type: 'theory', title: 'एक चिहान — सार', content: '<p>अध्याय सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/yek-chihan/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-12-6', chapterId: 'nep-12-6', type: 'theory', title: 'स्टिफन विलियम हकिङ — सार', content: '<p>अध्याय सार र मुख्य बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-7', chapterId: 'nep-12-7', type: 'theory', title: 'हामीलाई बोलाउँछन् हिमचुली — सार', content: '<p>अध्याय सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-8', chapterId: 'nep-12-8', type: 'theory', title: 'मातृत्व — सार', content: '<p>अध्याय सार र शब्दभण्डार।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-9', chapterId: 'nep-12-9', type: 'theory', title: 'गोर्खे — सार', content: '<p>अध्याय सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-10', chapterId: 'nep-12-10', type: 'theory', title: 'नेपाली पहिचान — सार', content: '<p>अध्याय सार र शब्दभण्डार।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/nepali-pahichan/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes</a></p>' },
  { id: 'note-nep-12-11', chapterId: 'nep-12-11', type: 'theory', title: 'सहकारी — सार', content: '<p>अध्याय सार र अभ्यास बुँदाहरू।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-nep-12-12', chapterId: 'nep-12-12', type: 'theory', title: 'जीवन मार्ग — सार', content: '<p>अध्याय सार र अभ्यास संकेत।</p><p>Source: <a href="https://nebplus2notes.com/class-12/nepali/" target="_blank" rel="noopener noreferrer">NEB Plus 2 Notes — Nepali</a></p>' },
  { id: 'note-cs-11-3-rn-1', chapterId: 'cs-11-3', type: 'theory', title: 'C Language — Overview (Readersnepal)', content: '<p>Comprehensive outline: history, features, control structures, arrays, strings, functions, pointers, structures, unions, and file handling.</p><p>Source: <a href="https://readersnepal.com/c-language" target="_blank" rel="noopener noreferrer">Readersnepal — C Language</a></p>' },
  { id: 'note-cs-11-3-rn-2', chapterId: 'cs-11-3', type: 'theory', title: 'C File Handling — Read & Display Records', content: '<p>Examples using FILE*, fopen, fscanf, printf, loops with EOF to read single/multiple records and filter output.</p><p>Source: <a href="https://readersnepal.com/read-and-display-records-in-c" target="_blank" rel="noopener noreferrer">Readersnepal — Read and Display Records in C</a></p>' },
  { id: 'note-cs-11-2-rn-1', chapterId: 'cs-11-2', type: 'theory', title: 'HTML — Overview (Readersnepal)', content: '<p>Definition, purpose, brief history, versions (HTML 1.0 to HTML5), workflow, and .html/.htm extensions.</p><p>Source: <a href="https://readersnepal.com/html" target="_blank" rel="noopener noreferrer">Readersnepal — HTML</a></p>' },
  { id: 'note-cs-11-2-rn-2', chapterId: 'cs-11-2', type: 'theory', title: 'CSS Types — Inline, Internal, External', content: '<p>Advantages of CSS and examples demonstrating inline styles, <style> block in head, and external stylesheet linkage.</p><p>Source: <a href="https://readersnepal.com/types-of-css" target="_blank" rel="noopener noreferrer">Readersnepal — Types of CSS</a></p>' },
  { id: 'note-cs-12-1-rn-1', chapterId: 'cs-12-1', type: 'theory', title: 'SQL — Overview & Basic Commands', content: '<p>DBMS types (Relational vs Non-Relational), SQL basics: CREATE TABLE, INSERT, SELECT with examples.</p><p>Source: <a href="https://readersnepal.com/sql" target="_blank" rel="noopener noreferrer">Readersnepal — SQL</a></p>' },
  { id: 'note-cs-12-1-rn-2', chapterId: 'cs-12-1', type: 'theory', title: 'DDL, DML, DCL — Examples', content: '<p>CREATE/DROP for schema and tables; SELECT/INSERT/UPDATE/DELETE for records; overview of control commands.</p><p>Source: <a href="https://readersnepal.com/ddl-dml-and-dcl-with-example" target="_blank" rel="noopener noreferrer">Readersnepal — DDL, DML, DCL</a></p>' },
  { id: 'note-cs-12-2-rn-1', chapterId: 'cs-12-2', type: 'theory', title: 'JavaScript — Basic Form Validation', content: '<p>Client-side validation using DOM APIs and alert for empty fields; onsubmit/onclick behaviors.</p><p>Source: <a href="https://readersnepal.com/form-validation-in-javascript" target="_blank" rel="noopener noreferrer">Readersnepal — Form Validation in JavaScript</a></p>' },
  { id: 'note-cs-12-2-rn-2', chapterId: 'cs-12-2', type: 'theory', title: 'PHP + MySQL — Store Form Data', content: '<p>Localhost setup with XAMPP, PHP file to connect and insert form inputs into MySQL via phpMyAdmin.</p><p>Source: <a href="https://readersnepal.com/how-to-insert-and-store-data-from-html-form-to-database" target="_blank" rel="noopener noreferrer">Readersnepal — Insert HTML Form to Database</a></p>' },
  { id: 'note-math-11-2-1', chapterId: 'math-11-2', type: 'theory', title: 'Matrices — Core Concepts', content: '<p>Matrix types: zero, identity, diagonal, symmetric; operations: addition, multiplication; determinant properties; inverse via adjoint; system of linear equations using Cramer’s rule.</p>' },
  { id: 'note-math-11-3-1', chapterId: 'math-11-3', type: 'theory', title: 'Calculus — Limits & Continuity', content: '<p>Limit definition, standard limits, continuity criteria, differentiability; basic derivative rules: power, product, quotient, chain.</p>' },
  { id: 'note-math-12-1-1', chapterId: 'math-12-1', type: 'theory', title: 'Permutation & Combination — Essentials', content: '<p>Permutation P(n,r)=n!/(n−r)!; Combination C(n,r)=n!/[r!(n−r)!]; applications to counting; Binomial Theorem: (a+b)^n=∑C(n,r)a^{n−r}b^r.</p>' },
  { id: 'note-math-12-2-1', chapterId: 'math-12-2', type: 'theory', title: 'Integrals — Basics', content: '<p>Indefinite integrals as antiderivatives; standard forms; definite integral properties; basic techniques: substitution, parts; area under curve.</p>' },
  { id: 'note-phy-11-4-1', chapterId: 'phy-11-4', type: 'theory', title: 'Laws of Motion — Summary', content: '<p>Newtons three laws; friction: static vs kinetic; circular motion: centripetal acceleration a= v^2/r; free-body diagrams for problem solving.</p>' },
  { id: 'note-phy-11-5-1', chapterId: 'phy-11-5', type: 'theory', title: 'Work, Energy & Power — Key Points', content: '<p>Work as W=F·s; kinetic and potential energy; work-energy theorem; conservation of mechanical energy; power P=dW/dt.</p>' },
  { id: 'note-phy-12-1-1', chapterId: 'phy-12-1', type: 'theory', title: 'Wave Optics — Overview', content: '<p>Interference: Youngs double-slit; diffraction: single-slit minima; polarization by selective absorption and reflection.</p>' },
  { id: 'note-phy-12-2-1', chapterId: 'phy-12-2', type: 'theory', title: 'Current Electricity — Essentials', content: '<p>Ohm’s law V=IR; series/parallel resistances; Kirchhoff’s rules; potentiometer applications for emf and internal resistance.</p>' },
  { id: 'note-phy-12-3-1', chapterId: 'phy-12-3', type: 'theory', title: 'Modern Physics — Highlights', content: '<p>Photoelectric effect and Einstein equation; Bohr model: quantized orbits; X-rays: production and properties.</p>' },
  { id: 'note-chem-11-3-1', chapterId: 'chem-11-3', type: 'theory', title: 'Chemical Bonding — Overview', content: '<p>Ionic vs covalent bonds; Lewis structures; VSEPR shapes; hybridization sp, sp2, sp3; bond polarity and intermolecular forces.</p>' },
  { id: 'note-chem-11-4-1', chapterId: 'chem-11-4', type: 'theory', title: 'States of Matter — Summary', content: '<p>Gas laws (Boyle, Charles); kinetic molecular theory; phase changes and phase diagrams; properties of liquids and solids.</p>' },
  { id: 'note-chem-12-1-1', chapterId: 'chem-12-1', type: 'theory', title: 'Volumetric Analysis — Basics', content: '<p>Titrations: acid-base, redox; indicators; standard solutions, normality/molarity; calculation of end-point and percent purity.</p>' },
  { id: 'note-chem-12-2-1', chapterId: 'chem-12-2', type: 'theory', title: 'Organic II — Key Reactions', content: '<p>Haloalkanes: nucleophilic substitution; alcohols/phenols: oxidation, esterification; ethers: Williamson synthesis; orientation and reactivity trends.</p>' },
  { id: 'note-bio-11-2-1', chapterId: 'bio-11-2', type: 'theory', title: 'Genetics — Core Ideas', content: '<p>Mendel’s laws; monohybrid and dihybrid crosses; genotype vs phenotype; DNA structure and replication basics.</p>' },
  { id: 'note-bio-12-1-1', chapterId: 'bio-12-1', type: 'theory', title: 'Human Physiology — Digest & Respire', content: '<p>Digestive organs and enzymes; respiratory mechanics and gas exchange; brief overview of circulation and excretion.</p>' },
  { id: 'note-bio-12-2-1', chapterId: 'bio-12-2', type: 'theory', title: 'Genetics & Evolution — Summary', content: '<p>Central dogma; variation and natural selection; Darwinian evolution; evidence from fossils and molecular biology.</p>' },
  { id: 'note-cs-12-3-1', chapterId: 'cs-12-3', type: 'theory', title: 'C Advanced — Pointers, Structures & Files', content: '<p>Pointers: declaration, dereferencing, pointer arithmetic; structures: definition and access; file handling: fopen/fclose, fprintf/fscanf.</p>' },
];

export const pastPapers: PastPaper[] = [
  {
    id: 'pp-phy-2080',
    subjectId: 'phy',
    chapterId: 'phy-11-1', 
    year: 2080,
    title: 'NEB Grade 11 Physics Model Question 2080',
    pdfUrl: 'https://readersnepal.com/neb-class-11-science-all-subject-model-question',
    hasSolutions: true,
  },
  {
    id: 'pp-chem-2079',
    subjectId: 'chem',
    chapterId: 'chem-11-1',
    year: 2079,
    title: 'NEB Grade 11 Chemistry 2079',
    pdfUrl: 'https://readersnepal.com/neb-class-11-science-all-subject-model-question',
    hasSolutions: false,
  },
  {
    id: 'pp-cs-2080',
    subjectId: 'cs',
    chapterId: 'cs-11-3',
    year: 2080,
    title: 'NEB Grade 11 Computer Science 2080',
    pdfUrl: 'https://readersnepal.com/neb-class-11-new-model-question-of-computer-science-2077',
    hasSolutions: true,
  },
  {
    id: 'pp-math-2078',
    subjectId: 'math',
    chapterId: 'math-11-1',
    year: 2078,
    title: 'NEB Grade 11 Mathematics 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-11-new-model-question-and-grid-of-all-subject-2077',
    hasSolutions: true,
  },
  {
    id: 'pp-phy-2078-12',
    subjectId: 'phy',
    chapterId: 'phy-12-1',
    year: 2078,
    title: 'NEB Grade 12 Physics Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-chem-2078-12',
    subjectId: 'chem',
    chapterId: 'chem-12-1',
    year: 2078,
    title: 'NEB Grade 12 Chemistry Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-cs-2078-12',
    subjectId: 'cs',
    chapterId: 'cs-12-1',
    year: 2078,
    title: 'NEB Grade 12 Computer Science Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-math-2078-12',
    subjectId: 'math',
    chapterId: 'math-12-2',
    year: 2078,
    title: 'NEB Grade 12 Mathematics Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-bio-2078-12',
    subjectId: 'bio',
    chapterId: 'bio-12-1',
    year: 2078,
    title: 'NEB Grade 12 Biology Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-nep-2078-12',
    subjectId: 'nep',
    chapterId: 'nep-12-5',
    year: 2078,
    title: 'NEB Grade 12 Nepali Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
  {
    id: 'pp-eng-2078-12',
    subjectId: 'eng',
    chapterId: 'eng-12-full',
    year: 2078,
    title: 'NEB Grade 12 English Board Exam 2078',
    pdfUrl: 'https://readersnepal.com/neb-class-12-all-subjects-board-exam-questions-2078',
    hasSolutions: false,
  },
];

export const mockTests: MockTest[] = [
  {
    id: 'test-phy-1',
    chapterId: 'phy-11-1',
    title: 'Units and Measurement - Practice Set 1',
    durationMinutes: 30,
    totalMarks: 20,
    difficulty: 'easy',
  },
  {
    id: 'test-chem-1',
    chapterId: 'chem-11-1',
    title: 'Stoichiometry Challenge',
    durationMinutes: 45,
    totalMarks: 30,
    difficulty: 'medium',
  },
  {
    id: 'test-cs-2',
    chapterId: 'cs-11-3',
    title: 'C Programming Mastery',
    durationMinutes: 40,
    totalMarks: 40,
    difficulty: 'hard',
  },
  {
    id: 'test-cs-3',
    chapterId: 'cs-11-2',
    title: 'HTML & CSS Basics',
    durationMinutes: 20,
    totalMarks: 20,
    difficulty: 'easy',
  },
];

export const questions: Question[] = [
  // Physics Questions
  {
    id: 'q-phy-1-1',
    testId: 'test-phy-1',
    type: 'multiple-choice',
    question: 'Which of the following is a fundamental unit?',
    options: ['Newton', 'Watt', 'Ampere', 'Joule'],
    correctAnswer: 'Ampere',
    marks: 1,
    explanation: 'Ampere is one of the 7 fundamental SI units.',
  },
  {
    id: 'q-phy-1-2',
    testId: 'test-phy-1',
    type: 'multiple-choice',
    question: 'The dimension of work is:',
    options: ['[MLT^-1]', '[ML^2T^-2]', '[MLT^-2]', '[ML^2T^-1]'],
    correctAnswer: '[ML^2T^-2]',
    marks: 1,
    explanation: 'Work = Force x Displacement = [MLT^-2] x [L] = [ML^2T^-2].',
  },
  
  // CS Questions - C Programming
  {
    id: 'q-cs-2-1',
    testId: 'test-cs-2',
    type: 'multiple-choice',
    question: 'Who is known as the father of C language?',
    options: ['James Gosling', 'Dennis Ritchie', 'Bjarne Stroustrup', 'Guido van Rossum'],
    correctAnswer: 'Dennis Ritchie',
    marks: 1,
    explanation: 'Dennis Ritchie developed C at Bell Labs in 1972.',
  },
  {
    id: 'q-cs-2-2',
    testId: 'test-cs-2',
    type: 'multiple-choice',
    question: 'Which of the following is the correct syntax to print "Hello World" in C?',
    options: ['print("Hello World");', 'echo "Hello World";', 'printf("Hello World");', 'Console.WriteLine("Hello World");'],
    correctAnswer: 'printf("Hello World");',
    marks: 1,
    explanation: 'printf() is the standard output function in C.',
  },
  {
    id: 'q-cs-2-3',
    testId: 'test-cs-2',
    type: 'short-answer',
    question: 'What is the output of: int a=5; printf("%d", a++);',
    correctAnswer: '5',
    marks: 2,
    explanation: 'The post-increment operator (a++) returns the value first (5) and then increments it.',
  },

  // CS Questions - HTML
  {
    id: 'q-cs-3-1',
    testId: 'test-cs-3',
    type: 'multiple-choice',
    question: 'What does HTML stand for?',
    options: ['Hyper Text Markup Language', 'High Text Markup Language', 'Hyper Tabular Markup Language', 'None of these'],
    correctAnswer: 'Hyper Text Markup Language',
    marks: 1,
    explanation: 'HTML stands for Hyper Text Markup Language.',
  },
  {
    id: 'q-chem-1-1',
    testId: 'test-chem-1',
    type: 'multiple-choice',
    question: 'Stoichiometry is primarily based on which law?',
    options: ['Law of conservation of mass', 'Boyle’s law', 'Raoult’s law', 'Henry’s law'],
    correctAnswer: 'Law of conservation of mass',
    marks: 1,
    explanation: 'Balanced equations reflect conservation of mass between reactants and products.',
  },
  {
    id: 'q-chem-1-2',
    testId: 'test-chem-1',
    type: 'multiple-choice',
    question: 'In the reaction: CH4 + 2O2 → CO2 + 2H2O, how many moles of water form per mole of methane?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    marks: 1,
    explanation: 'Coefficients indicate 1 mol CH4 produces 2 mol H2O.',
  },
  {
    id: 'q-chem-1-3',
    testId: 'test-chem-1',
    type: 'short-answer',
    question: 'Define limiting reagent.',
    correctAnswer: 'The reactant that is completely consumed first and limits product formation',
    marks: 2,
    explanation: 'It determines the maximum amount of product that can be formed.',
  },
  {
    id: 'q-chem-1-4',
    testId: 'test-chem-1',
    type: 'multiple-choice',
    question: 'What is the molar ratio of O2 to CH4 in complete combustion of methane?',
    options: ['1:1', '2:1', '1:2', '3:1'],
    correctAnswer: '2:1',
    marks: 1,
    explanation: 'CH4 + 2O2 → CO2 + 2H2O requires 2 moles of O2 per mole of CH4.',
  },
  {
    id: 'q-chem-1-5',
    testId: 'test-chem-1',
    type: 'multiple-choice',
    question: 'One mole of CO2 contains how many molecules?',
    options: ['6.022×10^22', '6.022×10^23', '3.00×10^23', '1.00×10^23'],
    correctAnswer: '6.022×10^23',
    marks: 1,
    explanation: 'One mole equals Avogadro’s number of molecules.',
  },
];

// Helper functions to simulate database access
export const getSubjects = async () => subjects;
export const getSubjectBySlug = async (slug: string) => subjects.find(s => s.slug === slug);
export const getChaptersBySubjectId = async (subjectId: string) => chapters.filter(c => c.subjectId === subjectId);
export const getChapterBySubjectSlugAndChapterNumber = async (subjectSlug: string, chapterNumber: number) => {
  const subject = subjects.find(s => s.slug === subjectSlug);
  if (!subject) return null;
  return chapters.find(c => c.subjectId === subject.id && c.number === chapterNumber);
};
export const getNotesByChapterId = async (chapterId: string) => notes.filter(n => n.chapterId === chapterId);
export const getPastPapers = async () => pastPapers;
export const getMockTests = async () => mockTests;
export const getMockTestById = async (id: string) => mockTests.find(t => t.id === id);
export const getQuestionsByTestId = async (testId: string) => questions.filter(q => q.testId === testId);
